apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app

    app.kubernetes.io/name: demo-app
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: multi-cloud-kubernetes-platform
    app.kubernetes.io/managed-by: kubectl

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

        app.kubernetes.io/name: demo-app
        app.kubernetes.io/instance: demo
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: multi-cloud-kubernetes-platform
        app.kubernetes.io/managed-by: kubectl

    spec:
      containers:
        - name: nginx
          image: nginx:1.27.5
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          volumeMounts:
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: nginx-config
          configMap:
            name: demo-app-config